version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: afs-assessment-app
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      SECRET_KEY: dev-secret-key-change-in-production
      DEBUG: "True"
      DATABASE_URL: sqlite:///instance/app_dev.db
      LOG_LEVEL: INFO
    volumes:
      - app_data:/app/instance
      - app_uploads:/app/static/uploads
      - app_logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  app_data:
    driver: local
  app_uploads:
    driver: local
  app_logs:
    driver: local
